### ISSUE TITLE
Create Character on every join/restart

### ISSUE THREAD

**Issue by Dimmies** [RedEM-RP/redemrp_skin#1]
After restarting server, when joining the server, it will ask you to create a character, even if you have characters already created. Seems that sometimes if you follow through and create a character and then rejoin the game (without restarting server) it will show the proper character list.

**Comment by amakuu** [comment]
Umm it's not an redemrp_skin issue i think?

**Comment by ghost** [comment]
I noticed it had something to do with the respawn script when I stopped the respawn script it stopped

**Comment by BlueberryRP** [comment]
same issuse. When i just clear a cache and start server, than i already have a character, but can't chose any and have just create a new one. But that is not redemrp_skin issuse and i will create a new issuse for identity.

**Comment by RPUK1** [comment]
We can choose characters made on our server, but it doesn't spawn the created character. Just the default ped

**Comment by amakuu** [comment]
try /loadskin after selecting a character

**Comment by kanersps** [comment]
Will look at this when I get time, not sure waht this could be for now
