### ISSUE TITLE
Crashing once getting to create a character

### ISSUE THREAD

**Issue by ItsAegeus** [RedEM-RP/redemrp_skin#2]
any time joining the server some players will get to make a name and then the character screen will show up but crash shortly after showing.

**Comment by Ashember** [comment]
Having the same issue, it does work intermittently, with server restarts but very unpredictable.

**Comment by mkondrac** [comment]
Add this in your server.cfg

`add_ace resource.redem command.add_principal allow`
`add_ace resource.redem command.add_ace allow`

**Comment by MidasCE** [comment]
Hi, I just come here to verify that this crash is happening to me too.

@mkondrac That doesn't solve the problem for me. (Actually it's needed to set it up for the main redEm resource)

**Comment by TheRealCrappyGamer** [comment]
I can confirm I have this same problem.

**Comment by ghost** [comment]
Mine works fine after applying a hot fix to the client lua

**Comment by TheRealCrappyGamer** [comment]
What is the hot fix? I just downloaded the latest branch 10 minutes ago.

**Comment by ghost** [comment]
Give me 5 mins il find it

**Comment by ghost** [comment]
Find this in your client Lua and replace it clear cache to be safe ```RegisterNetEvent('redemrp_skin:changeSex2')
AddEventHandler('redemrp_skin:changeSex2', function(model)
local model2 = model

RequestModel(model2)

Citizen.CreateThread(function() 
        local waiting = 0
        while not HasModelLoaded(model2) do
            waiting = waiting + 100
            Citizen.Wait(100)
            if waiting > 5000 then
                print("Could not load ped")
                break
            end
        end
        Citizen.InvokeNative(0xED40380076A31506, PlayerId(), model2)
            
       Citizen.InvokeNative(0x283978A15512B2FE,PlayerPedId(),true)
        SetModelAsNoLongerNeeded(model2)
        print("works")

    end)

end)```

**Comment by ghost** [comment]
Obviously remove the things before Register and after end)

**Comment by TheRealCrappyGamer** [comment]
That worked perfectly!

**Comment by ghost** [comment]
Glad to help 😉

**Comment by amakuu** [comment]
Download the newest version, and try again it should work now.
/close
