### ISSUE TITLE
skin save

### ISSUE THREAD

**Issue by JordanPANDA** [RedEM-RP/redemrp_skin#22]
i can't manage to save my skin when i reload the game (quit/reconnect) my character are fat and everything is messed up, i've tryed to put RCPclothing to edit skin etc but it don't save either, i came here to find a solution if possible or if you plan a better character creations (with more option)

Do you know how i can manage to force all skin/face/color/eyes/ped/etc change to save ?

Sorry for the time consuming and the noob answer and thanks for futur help

**Comment by amakuu** [comment]
correctly installing redemrp_skin saves skins.
/close
