### ISSUE TITLE
hair doesn't load

### ISSUE THREAD

**Issue by BlueberryRP** [RedEM-RP/redemrp_skin#8]
Hair doesn't load when joined to server
{"skin":"1","hair":"220","fat":"2","eye":"1","face":"1","sex":"male","faces":"1"}

**Comment by amakuu** [comment]
it is happening every time?
Even after you type /loadskin?

**Comment by BlueberryRP** [comment]
Always when i am connecting to server. Yes /loadskin help with it but my face change color to
![image](https://user-images.githubusercontent.com/58884050/70934984-ffdf6080-2060-11ea-8d56-b16cc1d5c000.png)

**Comment by amakuu** [comment]
because face 1 is black one.

**Comment by BlueberryRP** [comment]
> because face 1 is black one.

alright, i forgot this. But problem with hair if i don't use this command hair doesn't load

**Comment by amakuu** [comment]
weird....

**Comment by amakuu** [comment]
There is an issue with HDD drives, still we need to figure out how to fix it.

**Comment by BlueberryRP** [comment]
May be after loading character wait some time and after that loading skin?

**Comment by amakuu** [comment]
that its arleady done.

**Comment by BlueberryRP** [comment]
But may be after that wait a bit time and load again. Or just get components if got components from character == nil then load again?

**Comment by amakuu** [comment]
that's not how it works.

**Comment by BlueberryRP** [comment]
Hm, i just look for another hair and that loading fine after joining.

**Comment by BlueberryRP** [comment]
So and that hair loading fine right now. I think that was some problem but now gone.
