### ISSUE TITLE
Fixed problem with Missing Tables

### ISSUE THREAD

**Issue by MushroomFleet** [RedEM-RP/redemrp_skin#9]
Current instructions:
"2. Installation
First of all you need to insert the .sql file into your database.
Put the redemrp_skin into [redemrp] folder in your resources.
Add ensure redemrp_skin in server.cfg"

Missing instructions:
> Import 'skins.sql' to your redemrp mySQL DB.

While this might be obvious to some big brains, instructions must be detailed and contain every step required to install. The current instructions made no mention of it.
Thanks for closing my original issue, I already fixed it by doing this.

**Comment by ItsAegeus** [comment]
"First of all, you need to insert the .sql file into your database."
It is telling you to import the SQL. The only SQL in the whole resource.
It's not a big brain thing it's a common-sense thing to read and find the SQL. 

Please stop openings issues to cry.

**Comment by MushroomFleet** [comment]
yes i know. This was not in the instructions at the time. I already
completed it, but instead of "oh yeh maybe that might be a good to include
with the instructions" I got "WTF YOU DON@T INSTALL >SQL"
yes. yes. yes. tell me i'm crying. I don't know where you get that from.
My server is up and working fine and i'm very happy with it.


These problems everyone is having are not unique.
Maybe if the instructions were clear and didn't conflict, this problem
would not occur.
However I'm not the one getting emotional here.
A developer would not get irate because bugs are being reported. Be serious.
